[project]
name = "marcsleegers.com"
version = "1.0"
description = "This module contains both the static files and the source files used to generate marcsleegers.com"
readme = "README.md"
requires-python = "==3.14.*"
authors = [{ name = "Marc Sleegers" }]
license = "MIT"
dependencies = [
    "pelican",
    "markdown",
    "typogrify",
    "webassets",
    "beautifulsoup4",
    "cssmin",
    "pelican-webassets",
    "pelican-neighbors",
    "pelican-sitemap",
    "pelican-series",
    "pelican-render-math",
    "pelican-share-post",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
