[project]
name = "marcsleegers.com"
version = "2.0"
description = "This module contains both the static files and the source files used to generate marcsleegers.com"
readme = "README.md"
requires-python = "==3.14.*"
authors = [{ name = "Marc Sleegers" }]
license = "MIT"
dependencies = [
    "pelican",
    "markdown",
    "typogrify",
    "webassets",
    "beautifulsoup4",
    "pelican-webassets",
    "pelican-neighbors",
    "pelican-sitemap",
    "pelican-series",
    "pelican-render-math",
    "pelican-share-post",
    "pelican-readtime",
    "rcssmin>=1.2.2",
]
